version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: IQqjvq3w431!
      MYSQL_DATABASE: project_k
      MYSQL_USER: admin
      MYSQL_PASSWORD: IQqjvq3w431!
    ports:
      - "3307:3307"

  s3:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "4572:4572"

  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - s3
    environment:
      - AWS_ACCESS_KEY="AKIARUWRACK3VTUPUHW6"
      - AWS_SECRET_KEY="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"
      - AWS_REGION="eu-west-1"
      - AWS_BUCKET="project-k-templates"
